"""add questions table

Revision ID: 50945e993905
Revises: 5fa73db5a673
Create Date: 2026-09-06 11:27:50.274159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50945e993905'
down_revision: Union[str, Sequence[str], None] = '5fa73db5a673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer_1', sa.String(length=255), nullable=False),
    sa.Column('answer_2', sa.String(length=255), nullable=False),
    sa.Column('answer_3', sa.String(length=255), nullable=False),
    sa.Column('answer_4', sa.String(length=255), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
