"""Add max players to game rooms

Revision ID: 5fa73db5a673
Revises: f7cd82d58b91
Create Date: 2026-09-05 12:25:21.915811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa73db5a673'
down_revision: Union[str, Sequence[str], None] = 'f7cd82d58b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('max_players', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_rooms', 'max_players')
    # ### end Alembic commands ###
